/** Canonical MCP tool registry — single source for manifest and contract tests. */
export const MCP_TOOL_NAMES = [
  'save_memory',
  'update_memory',
  'delete_memory',
  'get_memory',
  'get_memory_by_codename',
  'search_memory',
  'get_memory_by_path',
  'get_context',
  'build_prompt',
  'list_projects',
  'list_tags',
  'link_memories',
  'list_relations',
  'toggle_favorite',
  'archive_memory',
  'get_graph_capabilities',
  'traverse_relations',
  'list_workspaces',
  'list_agents',
  'register_agent',
  'get_capabilities',
  'negotiate_capabilities',
  'submit_signal',
  'run_stewardship',
  'get_compression_status',
  'sync_pull',
  'sync_push',
  'sync_status',
] as const;

export type McpToolName = (typeof MCP_TOOL_NAMES)[number];
