import type { AgentClientProfile } from '../types/agent-client-profile.js';

/** SSOT external agent client profiles (ADR-030 Phase 15). */
export const AGENT_CLIENT_PROFILES: readonly AgentClientProfile[] = [
  {
    clientType: 'cursor',
    displayName: 'Cursor',
    vendor: 'Cursor',
    primaryProtocol: 'mcp-stdio',
    supportedProtocols: ['mcp-stdio', 'rest', 'grpc', 'websocket', 'sse'],
    mcp: {
      configPaths: ['.cursor/mcp.json'],
      requiredEnv: ['MCP_OWNER_ID'],
      setupCommand: 'npm run setup',
    },
    rest: {
      authMethods: ['api-key', 'jwt'],
      recommendedEndpoints: ['/capabilities', '/context', '/memory'],
    },
    grpc: { required: false, services: ['MemoryService', 'SearchService', 'ContextService'] },
    workspace: { required: true, registrationTool: 'register_agent' },
    handoff: { supportsMcpSaveMemory: true, recommendedTags: ['handoff'] },
    documentationUrl: 'https://docs.cursor.com/context/mcp',
  },
  {
    clientType: 'claude-code',
    displayName: 'Claude Code',
    vendor: 'Anthropic',
    primaryProtocol: 'mcp-stdio',
    supportedProtocols: ['mcp-stdio', 'rest', 'grpc'],
    mcp: {
      configPaths: ['.mcp.json', '.claude/settings.json'],
      requiredEnv: ['MCP_OWNER_ID'],
      setupCommand: 'npm run setup',
    },
    rest: {
      authMethods: ['api-key', 'jwt'],
      recommendedEndpoints: ['/capabilities', '/context'],
    },
    grpc: { required: false, services: ['MemoryService', 'ContextService'] },
    workspace: { required: true, registrationTool: 'register_agent' },
    handoff: { supportsMcpSaveMemory: true, recommendedTags: ['handoff'] },
  },
  {
    clientType: 'claude-desktop',
    displayName: 'Claude Desktop',
    vendor: 'Anthropic',
    primaryProtocol: 'mcp-stdio',
    supportedProtocols: ['mcp-stdio', 'rest'],
    mcp: {
      configPaths: ['claude_desktop_config.json'],
      requiredEnv: ['MCP_OWNER_ID'],
    },
    rest: {
      authMethods: ['api-key'],
      recommendedEndpoints: ['/capabilities', '/context'],
    },
    workspace: { required: true, registrationTool: 'register_agent' },
    handoff: { supportsMcpSaveMemory: true, recommendedTags: ['handoff'] },
  },
  {
    clientType: 'openai-api',
    displayName: 'OpenAI API',
    vendor: 'OpenAI',
    primaryProtocol: 'rest',
    supportedProtocols: ['rest', 'grpc'],
    rest: {
      authMethods: ['api-key'],
      recommendedEndpoints: ['/capabilities', '/context', '/memory'],
    },
    grpc: { required: false, services: ['MemoryService', 'SearchService'] },
    workspace: { required: true },
    handoff: { supportsMcpSaveMemory: false, recommendedTags: ['handoff'] },
  },
  {
    clientType: 'openai-agents-sdk',
    displayName: 'OpenAI Agents SDK',
    vendor: 'OpenAI',
    primaryProtocol: 'rest',
    supportedProtocols: ['rest', 'grpc'],
    rest: {
      authMethods: ['api-key'],
      recommendedEndpoints: ['/capabilities', '/context', '/ecosystem/clients'],
    },
    grpc: { required: false, services: ['MemoryService', 'ContextService'] },
    workspace: { required: true },
    handoff: { supportsMcpSaveMemory: false, recommendedTags: ['handoff', 'openai-agents'] },
    documentationUrl: 'https://platform.openai.com/docs/guides/agents',
  },
  {
    clientType: 'gemini-cli',
    displayName: 'Gemini CLI',
    vendor: 'Google',
    primaryProtocol: 'mcp-stdio',
    supportedProtocols: ['mcp-stdio', 'rest'],
    mcp: {
      configPaths: ['.gemini/settings.json'],
      requiredEnv: ['MCP_OWNER_ID'],
    },
    rest: {
      authMethods: ['api-key'],
      recommendedEndpoints: ['/capabilities', '/context'],
    },
    workspace: { required: true, registrationTool: 'register_agent' },
    handoff: { supportsMcpSaveMemory: true, recommendedTags: ['handoff'] },
  },
  {
    clientType: 'codex',
    displayName: 'OpenAI Codex',
    vendor: 'OpenAI',
    primaryProtocol: 'rest',
    supportedProtocols: ['rest', 'grpc', 'mcp-stdio'],
    rest: {
      authMethods: ['api-key'],
      recommendedEndpoints: ['/capabilities', '/context', '/memory'],
    },
    grpc: { required: false, services: ['MemoryService'] },
    workspace: { required: true },
    handoff: { supportsMcpSaveMemory: false, recommendedTags: ['handoff'] },
  },
  {
    clientType: 'continue',
    displayName: 'Continue',
    vendor: 'Continue',
    primaryProtocol: 'mcp-stdio',
    supportedProtocols: ['mcp-stdio', 'rest'],
    mcp: {
      configPaths: ['.continue/mcpServers'],
      requiredEnv: ['MCP_OWNER_ID'],
    },
    rest: {
      authMethods: ['api-key'],
      recommendedEndpoints: ['/capabilities', '/context'],
    },
    workspace: { required: true, registrationTool: 'register_agent' },
    handoff: { supportsMcpSaveMemory: true, recommendedTags: ['handoff'] },
  },
  {
    clientType: 'qwen-code',
    displayName: 'Qwen Code',
    vendor: 'Alibaba',
    primaryProtocol: 'rest',
    supportedProtocols: ['rest', 'mcp-stdio'],
    rest: {
      authMethods: ['api-key'],
      recommendedEndpoints: ['/capabilities', '/context'],
    },
    mcp: {
      configPaths: ['mcp.json'],
      requiredEnv: ['MCP_OWNER_ID'],
    },
    workspace: { required: true },
    handoff: { supportsMcpSaveMemory: true, recommendedTags: ['handoff'] },
  },
  {
    clientType: 'vscode-copilot',
    displayName: 'VS Code Copilot',
    vendor: 'Microsoft',
    primaryProtocol: 'mcp-stdio',
    supportedProtocols: ['mcp-stdio', 'rest'],
    mcp: {
      configPaths: ['.vscode/mcp.json'],
      requiredEnv: ['MCP_OWNER_ID'],
    },
    rest: {
      authMethods: ['api-key', 'jwt'],
      recommendedEndpoints: ['/capabilities'],
    },
    workspace: { required: true },
    handoff: { supportsMcpSaveMemory: true, recommendedTags: ['handoff'] },
  },
  {
    clientType: 'custom-rest',
    displayName: 'Custom REST Client',
    vendor: 'Generic',
    primaryProtocol: 'rest',
    supportedProtocols: ['rest', 'grpc'],
    rest: {
      authMethods: ['api-key', 'jwt', 'oauth'],
      recommendedEndpoints: ['/capabilities', '/ecosystem/clients'],
    },
    workspace: { required: false },
    handoff: { supportsMcpSaveMemory: false, recommendedTags: ['handoff'] },
  },
  {
    clientType: 'custom-mcp',
    displayName: 'Custom MCP Client',
    vendor: 'Generic',
    primaryProtocol: 'mcp-stdio',
    supportedProtocols: ['mcp-stdio', 'rest'],
    mcp: {
      configPaths: ['mcp.json'],
      requiredEnv: ['MCP_OWNER_ID'],
    },
    workspace: { required: true, registrationTool: 'register_agent' },
    handoff: { supportsMcpSaveMemory: true, recommendedTags: ['handoff'] },
  },
] as const;
